<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="wSCalculatorServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/wSCalculatorServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/wSCalculatorServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://calc/">
    <import location="CalculatorService.wsdl" namespace="http://calc/"/>
    <plnk:partnerLinkType name="CalculatorLinkType">
        <plnk:role name="CalculatorRole" portType="ns:Calculator"/>
    </plnk:partnerLinkType>
</definitions>

