<?xml version="1.0" encoding="UTF-8"?>
<definitions name="RequestEvalWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/BpelEvaluation/RequestEvalWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/BpelEvaluation/RequestEvalWSDL" xmlns:ns="http://xml.netbeans.org/schema/RequestEvalXmlSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/BpelEvaluation/RequestEvalWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/RequestEvalXmlSchema" schemaLocation="RequestEvalXmlSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="RequestEvalWSDLOperationRequest">
        <part name="request" type="ns:requestEval"/>
    </message>
    <message name="RequestEvalWSDLOperationResponse">
        <part name="response" type="ns:responseEval"/>
    </message>
    <portType name="RequestEvalWSDLPortType">
        <operation name="RequestEvalWSDLOperation">
            <input name="input1" message="tns:RequestEvalWSDLOperationRequest"/>
            <output name="output1" message="tns:RequestEvalWSDLOperationResponse"/>
        </operation>
    </portType>
    <binding name="RequestEvalWSDLBinding" type="tns:RequestEvalWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="RequestEvalWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/BpelEvaluation/RequestEvalWSDL"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/BpelEvaluation/RequestEvalWSDL"/>
            </output>
        </operation>
    </binding>
    <service name="RequestEvalWSDLService">
        <port name="RequestEvalWSDLPort" binding="tns:RequestEvalWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/RequestEvalWSDLService/RequestEvalWSDLPort"/>
        </port>
    </service>
</definitions>

