<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WriteDBWSServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WriteDBWSServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WriteDBWSServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://dbws/">
    <import location="writeDBWS/wsdl/WriteDBWSService.wsdl" namespace="http://dbws/"/>
    <plnk:partnerLinkType name="writeDBWSLinkType">
        <plnk:role name="writeDBWSRole" portType="ns:writeDBWS"/>
    </plnk:partnerLinkType>
</definitions>

